### ISSUE TITLE
[Bug]: Find strategies require $identifier not to be null

### ISSUE THREAD

**Issue by rjankiew** [pimcore/data-importer#263]
### Expected behavior

When using any location strategy, if identifier is not specified in row (is empty, null), it should not cause importer to freeze. This is probably related to my previous issue: https://github.com/pimcore/data-importer/issues/182#issuecomment-1162751185

### Actual behavior

Import freezes on a row without provided identifier value. 

### Steps to reproduce

Configure import using "attribute" location strategy. Use a file that has, in any row, an empty cell where attribute value used to search object should be. Run import.

**Comment by Corepex** [comment]
@rjankiew thanks for reporting this issue. 

Could you please provide us some more information on how we can reproduce this issue? (exact configuration steps etc) Furthermore it would be perfect if you could provide us a demo csv file to reproduce the issue.

thanks :)

**Comment by Corepex** [comment]
@rjankiew, any updates according to my comment?

**Comment by Corepex** [comment]
closed the ticket due to inactivity. feel free to reopen if there's something new.

**Comment by seybsen** [comment]
Hi @Corepex,

I encountered the same issue as described above in pimcore/data-importer 1.7.2:

Reproduction:

Excel-File:
[repro.xlsx](https://github.com/pimcore/data-importer/files/10766261/repro.xlsx)

Target Pimcore Class:
![image](https://user-images.githubusercontent.com/739688/219647062-a1bd27a3-0adf-49aa-bf7b-64f5e99373f4.png)


Importer Config:
![image](https://user-images.githubusercontent.com/739688/219646588-e8dc3a79-48bc-4d32-8eb7-8f81c6f5f95f.png)
![image](https://user-images.githubusercontent.com/739688/219646709-610598ed-2988-471c-84f7-30e31f77c3af.png)
![image](https://user-images.githubusercontent.com/739688/219646796-7ad41836-42b2-424e-843e-db77423048fc.png)
![image](https://user-images.githubusercontent.com/739688/219646872-d4dcbe3c-7d9f-4ba8-8338-c3e118886f8d.png)

Stacktrace:


```
supervisord_1    |  0/1 [>---------------------------]   0% < 1 sec/< 1 sec 40.5 MiBFailed to process "17": Pimcore\Bundle\DataImporterBundle\Tool\DataObjectLoader::loadByAttribute(): Argument #3 ($identifier) must be of type string, null given, called in /var/www/html/vendor/pimcore/data-importer/src/Resolver/Load/AttributeStrategy.php on line 70
supervisord_1    | #0 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Load/AttributeStrategy.php(70): Pimcore\Bundle\DataImporterBundle\Tool\DataObjectLoader->loadByAttribute('\\Pimcore\\Model\\...', 'someattribute', NULL, '', true, 1)
supervisord_1    | #1 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Load/AbstractLoad.php(87): Pimcore\Bundle\DataImporterBundle\Resolver\Load\AttributeStrategy->loadElementByIdentifier(NULL)
supervisord_1    | #2 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Resolver.php(159): Pimcore\Bundle\DataImporterBundle\Resolver\Load\AbstractLoad->loadElement(Array)
supervisord_1    | #3 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Resolver.php(179): Pimcore\Bundle\DataImporterBundle\Resolver\Resolver->loadElement(Array)
supervisord_1    | #4 /var/www/html/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(178): Pimcore\Bundle\DataImporterBundle\Resolver\Resolver->loadOrCreateAndPrepareElement(Array, true)
supervisord_1    | #5 /var/www/html/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(142): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processElement('repro', Array, Object(Pimcore\Bundle\DataImporterBundle\Resolver\Resolver), Array)
supervisord_1    | #6 /var/www/html/vendor/pimcore/data-importer/src/Command/ParallelProcessQueueCommand.php(82): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processQueueItem(17)
supervisord_1    | #7 /var/www/html/vendor/webmozarts/console-parallelization/src/Parallelization.php(489): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->runSingleCommand('17', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
supervisord_1    | #8 /var/www/html/vendor/webmozarts/console-parallelization/src/Parallelization.php(348): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->runTolerantSingleCommand('17', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
supervisord_1    | #9 /var/www/html/vendor/webmozarts/console-parallelization/src/Parallelization.php(274): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->executeMasterProcess(Object(Webmozarts\Console\Parallelization\ParallelizationInput), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
supervisord_1    | #10 /var/www/html/vendor/symfony/console/Command/Command.php(298): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
supervisord_1    | #11 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
supervisord_1    | #12 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
supervisord_1    | #13 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
supervisord_1    | #14 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
supervisord_1    | #15 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
supervisord_1    | #16 /var/www/html/bin/console(49): Symfony\Component\Console\Application->run()
supervisord_1    | #17 {main}
```

**Comment by mcop1** [comment]
Hello @seybsen , 
the problem is also mentioned here, right? Seems to be the same error: 
https://github.com/pimcore/data-importer/issues/232

**Comment by seybsen** [comment]
Yes, @mcop1, you're right

**Comment by mcop1** [comment]
Great, I linked your comment to the open issue - we will have a look at it.
