### ISSUE TITLE
Data Importer - Issue with brick field mapping

### ISSUE THREAD

**Issue by moiashvin** [pimcore/data-importer#65]
I have configured the Data Objects Importer to load a CSV file in pimcore.

Under Mappings  - I have mapped Source Attribute (from file) to Data Target using Type = Direct and Field Name = field in object brick.

Issue is when the process run, I get this exception

=============================================================================================================================== Process Output ================================================================================================================================
15:44:07 ERROR     [DATA-IMPORTER] Error processing element: Exception: Call to undefined static method getBysource.scopeBrick.puid in class DataObject\Concrete in /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php:753
Stack trace:
#0 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Load/AttributeStrategy.php(66): Pimcore\Model\DataObject\Concrete::__callStatic('getBysource.ITS...', Array)
#1 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Load/AbstractLoad.php(86): Pimcore\Bundle\DataImporterBundle\Resolver\Load\AttributeStrategy->loadElementByIdentifier('5304179000')
#2 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Resolver.php(159): Pimcore\Bundle\DataImporterBundle\Resolver\Load\AbstractLoad->loadElement(Array)
#3 /var/www/html/vendor/pimcore/data-importer/src/Resolver/Resolver.php(179): Pimcore\Bundle\DataImporterBundle\Resolver\Resolver->loadElement(Array)
#4 /var/www/html/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(153): Pimcore\Bundle\DataImporterBundle\Resolver\Resolver->loadOrCreateAndPrepareElement(Array)
#5 /var/www/html/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(132): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processElement('M4Y-JCAPRE-IMPO...', Array, Object(Pimcore\Bundle\DataImporterBundle\Resolver\Resolver), Array)
#6 /var/www/html/vendor/pimcore/data-importer/src/Command/ParallelProcessQueueCommand.php(82): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processQueueItem(200)
#7 /var/www/html/vendor/webmozarts/console-parallelization/src/Parallelization.php(489): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->runSingleCommand('200', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/webmozarts/console-parallelization/src/Parallelization.php(442): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->runTolerantSingleCommand('200', Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/webmozarts/console-parallelization/src/Parallelization.php(269): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->executeChildProcess(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(299): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(996): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(295): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(167): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/bin/console(46): Symfony\Component\Console\Application->run()
#17 {main}

Can you please help.

**Comment by moiashvin** [comment]
was a mapping issue.
