### ISSUE TITLE
Data Objects Importer - Transformation Pipeline "as Date" not working

### ISSUE THREAD

**Issue by shaselboeck** [pimcore/data-importer#77]
An error "Argument pimcore/data-hub#1 ($flightArrival) must be of type ?Carbon\Carbon, DateTime given" occurs during the import (as Date -> Format "d.m.Y H:i" to Data Component Date & Time)

```
0/12 [>---------------------------]   0% < 1 sec/< 1 sec 20.0 MiBFailed to process "1579": Pimcore\Model\DataObject\Objectbrick\Data\TravelPositionFlight::setFlightArrival(): Argument pimcore/data-hub#1 ($flightArrival) must be of type ?Carbon\Carbon, DateTime given, called in /srv/www/domain.de/htdocs/vendor/pimcore/data-importer/src/Mapping/DataTarget/Direct.php on line 68
#0 /srv/www/domain.de/htdocs/vendor/pimcore/data-importer/src/Mapping/DataTarget/Direct.php(68): Pimcore\Model\DataObject\Objectbrick\Data\TravelPositionFlight->setFlightArrival()
pimcore/data-hub#1 /srv/www/domain.de/htdocs/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(178): Pimcore\Bundle\DataImporterBundle\Mapping\DataTarget\Direct->assignData()
pimcore/data-hub#2 /srv/www/domain.de/htdocs/vendor/pimcore/data-importer/src/Processing/ImportProcessingService.php(132): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processElement()
pimcore/data-hub#3 /srv/www/domain.de/htdocs/vendor/pimcore/data-importer/src/Command/ParallelProcessQueueCommand.php(82): Pimcore\Bundle\DataImporterBundle\Processing\ImportProcessingService->processQueueItem()
pimcore/data-hub#4 /srv/www/domain.de/htdocs/vendor/webmozarts/console-parallelization/src/Parallelization.php(482): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->runSingleCommand()
pimcore/data-hub#5 /srv/www/domain.de/htdocs/vendor/webmozarts/console-parallelization/src/Parallelization.php(348): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->runTolerantSingleCommand()
pimcore/data-hub#6 /srv/www/domain.de/htdocs/vendor/webmozarts/console-parallelization/src/Parallelization.php(274): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->executeMasterProcess()
pimcore/data-hub#7 /srv/www/domain.de/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(299): Pimcore\Bundle\DataImporterBundle\Command\ParallelProcessQueueCommand->execute()
pimcore/data-hub#8 /srv/www/domain.de/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(996): Symfony\Component\Console\Command\Command->run()
pimcore/data-hub#9 /srv/www/domain.de/htdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand()
pimcore/data-hub#10 /srv/www/domain.de/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(295): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
pimcore/data-hub#11 /srv/www/domain.de/htdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun()
pimcore/data-hub#12 /srv/www/domain.de/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(167): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
pimcore/data-hub#13 /srv/www/domain.de/htdocs/bin/console(46): Symfony\Component\Console\Application->run()
pimcore/data-hub#14 {main}
```

**Comment by dvesh3** [comment]
fixed already pimcore/data-importer#62

**Comment by chluehr** [comment]
Related / similar? (pimcore 10.1.1 / importer 1.1.4)

```
Pimcore\Model\DataObject\REDACTED::setREDACTED(): Argument #1 ($redacted) must be of type ?Carbon\Carbon, string given, called in /redacted/vendor/pimcore/data-importer/src/Mapping/DataTarget/Direct.php on line 5
  0
```

**Comment by fashxp** [comment]
hmm, not sure. can you create a new ticket and share more details to reproduce? 
like mapping, import data

thx.

**Comment by chluehr** [comment]
@fashxp My bad - figured out my dataset had an empty date cell somewhere, and those lead to the aforementioned code errors!
